Implement job queue in the framework - Closes #994
LiskHQ/lisk-service pull request #1019
Opened 2022-03-16 09:10 UTC by nagdahimanshu

### What was the problem?
This PR resolves #994 

### How was it solved?
- [ ] Add queue implementation to the service framework
- [ ] Publish latest service framework to GitHub
- [ ] A custom Redis URL supported
- [ ] Add functional tests
- [ ] Code refactor to use latest framework

### How was it tested?
Local + Jenkins

2022-03-17 09:09 UTC, sameersubudhi approved these changes
LGTM 👍

2022-03-22 13:30 UTC, MichalTuleja requested changes

2022-03-22 13:30 UTC, MichalTuleja commented on framework/test/functional/queue.test.js
> +	const redisEndpoint = 'redis://localhost:6379/0';
I think that should be configurable, depending on the CI server:
```suggestion
	const redisEndpoint = process.env.REDIS_URL || 'redis://localhost:6379/0';
```

2022-03-22 13:36 UTC, MichalTuleja approved these changes
Thanks @nagdahimanshu 👍

2022-03-22 13:36 UTC, merged