Create blockchain coordinator - Closes #997
LiskHQ/lisk-service pull request #1044
Opened 2022-03-31 20:23 UTC by nagdahimanshu

### What was the problem?
This PR resolves #997 

### How was it solved?
TODO

### How was it tested?
Local

2022-04-08 07:45 UTC, sameersubudhi commented on services/blockchain-indexer/shared/blocks.js
> +						.filter(s => s.moduleID === txn.moduleID && s.assetID === txn.assetID);
```suggestion
					const assetSchema = schema.transactionsAssets
						.find(s => s.moduleID === txn.moduleID && s.assetID === txn.assetID);
```

2022-04-10 23:01 UTC, sameersubudhi requested changes
Please address the following concerns.

2022-04-11 01:27 UTC, nagdahimanshu commented on services/blockchain-indexer/shared/indexer/accountIndex.js
> +};
Done!

2022-04-11 08:42 UTC, sameersubudhi commented on services/blockchain-coordinator/app.js
> +		appBlockNew: (payload) => Signals.get('newBlock').dispatch(payload.block),
Please ignore the above comment. The above implementation seems to be correct.

2022-04-11 12:34 UTC, sameersubudhi requested changes

2022-04-11 12:34 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/accountIndex.js
>  	const [genesisBlock] = await getBlockByHeight(await getGenesisHeight(), true);
This could make use of the `getGenesisAccounts` method. Let us discuss this on the call.

2022-04-11 12:34 UTC, sameersubudhi commented on services/blockchain-coordinator/shared/scheduler.js
> +});
Kindly update the config to use the same properties and environment variables across both `coordinator` and `indexer` microservices. Also, please update the config for the queue name as constants in both the microservices.

```suggestion
const blockIndexQueue = new Queue('Blocks', config.endpoints.messageQueue, {
	defaultJobOptions: config.queue.defaultJobOptions,
});

const accountIndexQueue = new Queue('Accounts', config.endpoints.messageQueue, {
	defaultJobOptions: config.queue.defaultJobOptions,
});
```

2022-04-11 14:02 UTC, MichalTuleja approved these changes

2022-04-11 14:02 UTC, merged