Move transaction statistics to a separate microservice - Closes #999
LiskHQ/lisk-service pull request #1059
Opened 2022-04-19 18:29 UTC by nagdahimanshu

### What was the problem?
This PR resolves #999 

### How was it solved?
- [ ] Create new service `transaction-statistics`
- [ ] Refactor/Migrate code:
  - [ ] Methods
  - [ ] Current implementation of statistics
  - [ ] Mysql
- [ ] Use data service to retrieve transactions

### How was it tested?
Local

2022-04-21 22:06 UTC, sameersubudhi reviewed
Please update the Makefile to include `blockchain-coordinator` and `transaction-statistics` microservices.

2022-04-21 22:19 UTC, nagdahimanshu commented
> Please update the Makefile to include `blockchain-coordinator` and `transaction-statistics` microservices.

Done

2022-04-22 10:29 UTC, sameersubudhi requested changes
Please consider the following. Also, there are many logs with the following errors:
`2022-04-22T12:26:16.605 ERROR [mysql] ER_CON_COUNT_ERROR: Too many connections`.

2022-04-22 10:29 UTC, sameersubudhi commented on services/transaction-statistics/config.js
> +	historyLengthDays: Number(process.env.TRANSACTION_STATS_HISTORY_LENGTH_DAYS || 365),
```suggestion
	historyLengthDays: Number(process.env.TRANSACTION_STATS_HISTORY_LENGTH_DAYS || 366),
```

2022-04-22 10:29 UTC, sameersubudhi commented on services/transaction-statistics/config.js
> +	// limiter: {},
Please remove them if they're not used anywhere.

2022-04-22 10:29 UTC, sameersubudhi commented on services/transaction-statistics/shared/transactionStatistics.js
> +	config.Queue.defaultJobOptions,
```suggestion
	config.queue.defaultJobOptions,
```

2022-04-22 10:53 UTC, nagdahimanshu commented
> Please consider the following. Also, there are many logs with the following errors:

@sameersubudhi I updated the MySql docker-compose file to increase the default connection limit to 200. Can you try again by pulling the latest changes?

2022-04-25 09:35 UTC, sameersubudhi requested changes
Please add the logic to start computing the stats only after the indexer sends out an event confirming that the index is completely up-to-date.

2022-04-25 13:11 UTC, sameersubudhi commented on services/transaction-statistics/config.js
> +config.httpTimeout = Number(process.env.LISK_CORE_CLIENT_TIMEOUT) || 30; // in seconds
This config property is getting used anywhere, please remove it if it is unnecessary.

2022-04-25 21:13 UTC, sameersubudhi approved these changes
Thank you for the changes. Great job! 🎉

2022-04-25 21:14 UTC, merged