Update metadata responses - Closes #1222
LiskHQ/lisk-service pull request #1224
Opened 2022-08-17 11:55 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1222 

### How was it solved?

- [ ] Update gateway:
  - [ ] Response mappings
  - [ ] Params mapping
- [ ] Update `app-registry` service
  - [ ] Controller 
  - [ ] implementation to retrieve metadata information
- [ ] Integration tests are up-to-date
- [ ] The swagger specification reflects the above changes

### How was it tested?
Local

2022-08-19 12:47 UTC, sameersubudhi requested changes

2022-08-19 13:08 UTC, sameersubudhi requested changes

2022-08-19 13:08 UTC, sameersubudhi commented on services/gateway/sources/version3/mappings/blockchainAppMetadata.js
> +	appNodes: '=',
Can we also explicitly declare the structure for the `explorers` and `appNodes` properties like we did for `serviceURLs` here?

2022-08-19 13:08 UTC, sameersubudhi commented on services/gateway/sources/version3/mappings/blockchainAppTokenMetadata.js
> +	denomUnits: '=',
Same as above.

2022-08-19 13:08 UTC, sameersubudhi commented on services/blockchain-app-registry/shared/metadata.js
> +	const [{ count: total }] = await applicationsDB.rawQuery('SELECT COUNT(chainName) as count from applications');
```suggestion
	const [{ total }] = await applicationsDB.rawQuery('SELECT COUNT(chainName) as total from applications');
```

2022-08-19 13:08 UTC, sameersubudhi commented on services/blockchain-app-registry/shared/metadata.js
> +	const [{ count: total }] = await applicationsDB.rawQuery('SELECT COUNT(chainName) as count from applications');
```suggestion
	const [{ total }] = await applicationsDB.rawQuery('SELECT COUNT(chainName) as total from applications');
```

2022-08-19 13:08 UTC, sameersubudhi commented on services/blockchain-app-registry/shared/metadata.js
> +	const [{ count: total }] = await applicationsDB.rawQuery('SELECT COUNT(tokenName) as count from tokens');
```suggestion
	const [{ total }] = await applicationsDB.rawQuery('SELECT COUNT(tokenName) as total from tokens');
```

2022-08-19 16:06 UTC, sameersubudhi requested changes

2022-08-19 16:06 UTC, sameersubudhi commented on services/blockchain-app-registry/shared/metadata.js
> +				{ network: tokenMeta.network, chainID: 1 },
Why do we have the `chainID` hardcoded here?

2022-08-22 09:09 UTC, priojeetpriyom approved these changes

2022-08-22 10:11 UTC, priojeetpriyom approved these changes

2022-08-22 10:12 UTC, merged