Use Lisk Core node version instead of protocol version - Closes #117 Closes #126
LiskHQ/lisk-service pull request #127
Opened 2020-10-01 15:08 UTC by sameersubudhi

### What was the problem?
This PR resolves #117 #126 

### How was it solved?

- [x] Replaced Lisk Core `protocol` version with the Lisk Core `node` version
- [x] Used `semver` npm package for semantic version comparision
- [x] Move the Lisk Core node version check from the controller to the service layer

### How was it tested?
Local + Jenkins

2020-10-05 09:25 UTC, MichalTuleja requested changes

2020-10-05 09:25 UTC, MichalTuleja commented on services/core/shared/coreVersionCompatibility.js
> +	'3.0.0': coreVersion300.paramMappersCoreV3,
Use the full Lisk Core version name ie. `3.0.0-beta.0`

2020-10-05 09:25 UTC, MichalTuleja commented on services/core/shared/coreVersionCompatibility.js
> +	coreMinVersion = semver.coerce(version).version.charAt(0).concat('.0.0');
Make this comparison based on semver, esp. suffixes like `-beta.x`.

2020-10-06 07:55 UTC, nagdahimanshu approved these changes

2020-10-06 17:05 UTC, MichalTuleja approved these changes

2020-10-06 17:06 UTC, merged