Extend off-chain metadata endpoint
LiskHQ/lisk-service pull request #1331
Opened 2022-11-14 16:54 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1325 

### How was it solved?

- [ ] isDefault: boolean based request query params is supported
- [ ] integration tests are up-to-date
- [ ] Swagger is up-to-date

### How was it tested?
Local

2022-11-14 23:22 UTC, sameersubudhi requested changes

2022-11-14 23:22 UTC, sameersubudhi commented on services/gateway/apis/http-version3/methods/blockchainAppsMetadata.js
> +		isDefault: { optional: true, type: 'boolean', min: 1, pattern: regex.BOOLEAN },
We do not really need a patter check for the `boolean` type. Instead, optionally, enforce the `convert` property to `false`, which also happens to be the default value.

Ref: https://github.com/icebob/fastest-validator#boolean

```suggestion
		isDefault: { optional: true, type: 'boolean', convert: false },
```

2022-11-16 11:44 UTC, priojeetpriyom approved these changes

2022-11-16 11:44 UTC, priojeetpriyom commented on services/blockchain-app-registry/shared/metadata.js
> +	if (!('isDefault' in params) || params.isDefault) {
Alternatively, could we write like below?

```suggestion
	if (params.isDefault !== false) {
```

2022-11-16 11:44 UTC, priojeetpriyom commented on services/blockchain-app-registry/shared/metadata.js
> +	if (!params.isDefault && blockchainAppsMetadata.data.length < params.limit) {
Alternatively, could we write like below?

```suggestion
	if (params.isDefault !== true && blockchainAppsMetadata.data.length < params.limit) {
```

2022-11-16 15:14 UTC, sameersubudhi approved these changes
LGTM 👍

2022-11-16 15:51 UTC, sameersubudhi approved these changes

2022-11-16 15:51 UTC, merged