Migrate accounts to blockchain data storage - Closes#136
LiskHQ/lisk-service pull request #152
Opened 2020-10-20 07:57 UTC by nagdahimanshu

### What was the problem?
This PR resolves #136 

### How was it solved?
- [ ] Account data is stored in cache and persistent data is used only for a defined number of accounts
- [ ] Accounts that are not stored are retrieved directly from blockchain

### How was it tested?
Local + Jenkins

2020-10-23 13:52 UTC, MichalTuleja requested changes

2020-10-23 13:52 UTC, MichalTuleja commented on services/core/shared/pouchdb.js
> +		if (!doc._id) doc._id = doc.id || doc.address;
I think `doc.address` is too specific here. Please define `doc._id` in the account code instead.

2020-10-23 13:52 UTC, MichalTuleja commented on services/core/shared/pouchdb.js
> +		if (!doc._id) doc._id = doc.id || doc.address;
I think `doc.address` is too specific here. Please define `doc._id` in the account code instead.

2020-10-23 13:52 UTC, MichalTuleja commented on services/core/shared/pouchdb.js
> +			if (!doc._id) doc._id = doc.id || doc.address;
I think `doc.address` is too specific here. Please define `doc._id` in the account code instead.

2020-10-23 13:52 UTC, MichalTuleja commented on services/core/shared/core/compat/sdk_v2/delegateCache.js
> +	const response = await core.getDelegates({ limit, offset: delegateList.length });
Good point 👍

2020-10-23 13:52 UTC, MichalTuleja commented on services/core/shared/core/compat/index.js
> +};
I think using a proxy here wouldn't hurt, esp. that some functions that are not available in certain versions of the SDK compatibility layer. But let's keep it as it is for now, and be open for a discussion around here.

2020-10-28 09:13 UTC, sameersubudhi commented on services/core/app.js
> +
Kindly remove the commented code.

2020-10-28 09:14 UTC, sameersubudhi commented on services/core/app.js
> +	// await core.init();
Same as above.

2020-10-28 09:16 UTC, sameersubudhi commented on services/core/events/blockchain.js
> +					core.removeOrphanedBlocks(202);
Consider referring to the `config.cacheNumOfBlocks` property instead of hardcoding.

2020-10-28 09:25 UTC, sameersubudhi commented on services/core/shared/core/accounts.js
> +						}
```suggestion
						try{
							if (Number(a[sortProp]) >= 0 && Number(b[sortProp]) >= 0) {
								compareResult = Number(a[sortProp]) - Number(b[sortProp]);
							} 
						} catch (err) {
							compareResult = a[sortProp].localCompare(b[sortProp]);
						}
```

2020-10-28 09:28 UTC, sameersubudhi commented on services/core/shared/core/index.js
> +};
Consider removing this section completely.

2020-10-28 09:29 UTC, sameersubudhi commented on services/core/shared/core/index.js
> +	init,
Same as above.

2020-10-28 09:30 UTC, sameersubudhi commented on services/core/shared/core/index.js
> +	init,
Same as above

2020-10-28 09:34 UTC, sameersubudhi commented on services/core/shared/pouchdb.js
> +	// const cLogger = dbLogger[collectionName];
Kindly consider using the `cLogger`. Refer https://github.com/LiskHQ/lisk-service/pull/146.

2020-10-28 09:35 UTC, sameersubudhi requested changes
Kindly find my review comments.

2020-10-28 13:08 UTC, nagdahimanshu commented on services/core/shared/core/accounts.js
> +						}
Updated

2020-10-28 13:33 UTC, sameersubudhi approved these changes
LGTM! 👍

2020-10-29 15:32 UTC, MichalTuleja approved these changes
LGTM :)

2020-10-29 15:32 UTC, merged