Unable to index mainnet genesis block
LiskHQ/lisk-service pull request #1526
Opened 2023-03-02 18:15 UTC by priojeetpriyom

### What was the problem?
This PR resolves #1517

### How was it solved?
- [x] Filter out genesis assets from the genesis block
- [x] Implement methods to retrieve genesis assets for PoS module
  - [x] getPoSGenesisValidators
  - [x] getPoSGenesisStakers
- [x] Updated indexes for `events/eventTopics` table
- [x] Update swagger specification
- [x] Fix issues with invoking the `/blockchain/apps` endpoint when running Lisk Service against sidechains

### How was it tested?
- [x] Local

2023-03-03 15:13 UTC, nagdahimanshu commented on services/blockchain-indexer/shared/constants.js
> +	return module.assets[0].data;
```suggestion
	const [asset = {}] = (metadata.modules.find(metaData => metaData.name === moduleName)).assets;
	return asset.data;
```

2023-03-03 15:22 UTC, nagdahimanshu commented on services/blockchain-indexer/shared/utils/genesisBlock.js
> +const path = require('path');
```suggestion
const fs = require('fs');
const json = require('big-json');
const path = require('path');
const BluebirdPromise = require('bluebird');

const logger = require('lisk-service-framework').Logger();
const { codec } = require('@liskhq/lisk-codec');
```

2023-03-03 15:22 UTC, nagdahimanshu commented on services/blockchain-indexer/shared/utils/genesisBlock.js
> +const logger = Logger();
```suggestion
```

2023-03-09 15:39 UTC, sameersubudhi requested changes

2023-03-09 15:39 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/genesisBlock.js
> +		return { header: block.header, transactions: block.transactions, assets: [] };
```suggestion
		// Filter out assets from genesis block and assign empty array
		return { ...block, assets: [] };
```

2023-03-09 15:39 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/genesisBlock.js
> +const getPoSGenesisStakers = async () => {
This should be implemented in a generic manner where the genesis block is fetched via the getBlock or getGenesisBlock method. Let's discuss this offline.

2023-03-09 15:39 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/genesisBlock.js
> +const getPoSGenesisValidators = async () => {
Same as above.

2023-03-09 15:39 UTC, sameersubudhi commented on services/gateway/apis/http-version3/methods/blockAssets.js
> +			description: 'Returns block assets data. Block assets are always returned empty for genesis height.',
```suggestion
			description: 'Returns block assets data. Assets are always returned empty for the genesis height.',
```

2023-03-09 15:39 UTC, sameersubudhi commented on services/gateway/apis/http-version3/swagger/definitions/blocks.json
> +                    }
```suggestion
                    },
                    "required": [
                        "module",
                        "data"
                    ],
```

2023-03-09 15:39 UTC, sameersubudhi commented on services/gateway/apis/http-version3/swagger/definitions/blocks.json
> +                            }
```suggestion
                            },
                            "description": "The data object schema varies by module. The exact schema can be found from the `/schemas`endpoint."
```

2023-03-09 16:30 UTC, sameersubudhi requested changes

2023-03-09 16:30 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/genesisBlock.js
> +const getGenesisBlock = async (includeGenesisAssets) => {
```suggestion
const getGenesisBlock = async (isIncludeAssets = false) => {
```

2023-03-09 16:30 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/genesisBlock.js
> +			assets: includeGenesisAssets ? block.assets : [],
```suggestion
			assets: isIncludeAssets ? block.assets : [],
```

2023-03-09 16:30 UTC, sameersubudhi commented on services/gateway/apis/http-version3/swagger/definitions/blocks.json
> +                            "description": "The data object schema varies by module. The exact schema can be found from the `/schemas`endpoint."
```suggestion
                            "description": "The data object schema varies by module. The exact schema can be found from the `/schemas` endpoint."
```

2023-03-09 16:33 UTC, nagdahimanshu approved these changes

2023-03-09 16:46 UTC, sameersubudhi approved these changes
LGTM 👍

2023-03-09 16:46 UTC, merged