Include status in transactions dry run response
LiskHQ/lisk-service pull request #1549
Opened 2023-03-22 18:02 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1543 #1547 

### How was it solved?

- [x] network param support CSV inputs and return all the valid entries in the response
- [x] Extend the response to include status corresponding the result value
- [x] Gateway mappings are up-to-date
- [x] All the possible data fields are explicitly mapped
  - [x] result
  - [x] status
  - [x] events
  - [x] errorMessage
- [x] Swagger is up-to-date
- [x] Integration tests (schemas) are up-to-date

### How was it tested?
Local

2023-03-22 22:38 UTC, sameersubudhi requested changes

2023-03-22 22:38 UTC, sameersubudhi commented on services/blockchain-indexer/shared/dataService/business/transactionsDryRun.js
> +			.find(e => TRANSACTION_VERIFY_RESULT[e] === response.result),
```suggestion
			.find(e => TRANSACTION_VERIFY_RESULT[e] === response.result)
			.toLowerCase(),
```

2023-03-22 22:38 UTC, sameersubudhi commented on services/gateway/sources/version3/transactionsDryRun.js
>  		meta: '=',
```suggestion
		meta: {},
```

2023-03-22 22:41 UTC, sameersubudhi approved these changes

2023-03-23 10:23 UTC, priojeetpriyom approved these changes

2023-03-23 10:23 UTC, merged