numberOfEvents missing in new block event payload
LiskHQ/lisk-service pull request #1556
Opened 2023-03-28 12:20 UTC by priojeetpriyom

### What was the problem?
This PR resolves #1545 

### How was it solved?
- [x] Fetch events from connector if not available in db
- [x] Resolve block reward from events
- Update integration test schema for blocks
    - [x] Fix failing test
    - [x] Set minimum number of events to 1 as every block has atleast 1 event.
    - [x] Allow null for reward value as genesis block does not have reward event.

### How was it tested?
- [x] Local

2023-03-28 12:34 UTC, sameersubudhi requested changes

2023-03-28 12:34 UTC, sameersubudhi commented on services/blockchain-indexer/shared/dataService/business/blocks.js
> +				reward: blockRewardEvent ? blockRewardEvent.data.amount : undefined,
```suggestion
				reward: blockRewardEvent ? blockRewardEvent.data.amount : null,
```

2023-03-28 14:16 UTC, sameersubudhi approved these changes
LGTM 👍

2023-03-29 07:51 UTC, vardan10 approved these changes

2023-03-29 07:54 UTC, merged