Rename token module endpoints
LiskHQ/lisk-service pull request #1557
Opened 2023-03-28 14:21 UTC by vardan10

### What was the problem?
This PR resolves #1555

### How was it solved?

- [x] - Renamed GET /tokens to GET /token/balances and updated RPC endpoint.
- [x] - Renamed GET /tokens/summary to GET /token/summary and updated RPC endpoint.
- [x] - Updated the endpoints in integration tests
- [x] - Updated swagger docs

### How was it tested?

- [x] Swagger API call
- [x] Running testcases

2023-03-28 14:45 UTC, nagdahimanshu commented on services/gateway/apis/http-version3/methods/modules/token/tokens.js
> +	swaggerApiPath: '/token/balances',
Can we also rename the file to `tokenBalances`

2023-03-28 14:50 UTC, sameersubudhi requested changes

2023-03-28 14:50 UTC, sameersubudhi commented on tests/integration/api_v3/http/tokens.test.js
> +const endpoint = `${baseUrlV3}/token`;
Also, please rename the file accordingly. And, kindly do not forget to make the corresponding changes in the RPC tests.
```suggestion
const endpoint = `${baseUrlV3}/token/balances`;
```

2023-03-28 14:50 UTC, sameersubudhi commented on tests/integration/api_v3/http/tokensSummary.test.js
Corresponding update missing in the RPC tests.

2023-03-28 14:50 UTC, sameersubudhi commented on services/gateway/tests/constants/registerApi.js
> +				'get.token.balances': 'indexer.tokens',
Could we also rename the methods within indexer microservice from `tokens` to `token.balances`? Please leave the method names in connector as is.

2023-03-29 09:40 UTC, sameersubudhi commented on tests/integration/api_v3/http/tokensSummary.test.js
Rename file to `tests/integration/api_v3/http/tokenSummary.test.js`.

2023-03-29 09:41 UTC, sameersubudhi commented on services/gateway/apis/http-version3/methods/modules/token/tokensSummary.js
Rename file to `services/gateway/apis/http-version3/methods/modules/token/tokenSummary.js`.

2023-03-29 09:41 UTC, sameersubudhi commented on services/gateway/apis/http-version3/methods/modules/token/tokens.js
Rename file to `services/gateway/apis/http-version3/methods/modules/token/tokenBalances.js`.

2023-03-29 12:41 UTC, sameersubudhi approved these changes
LGTM 👍

2023-03-29 12:47 UTC, nagdahimanshu approved these changes
LGTM 👍

2023-03-29 14:31 UTC, merged