Remove posting transaction to lisk service page  - Closes #1573
LiskHQ/lisk-service pull request #1585
Opened 2023-04-20 10:27 UTC by chris529

Closes issue # 1573 Remove posting transactions page in the Lisk docs repo.

2023-04-20 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-service?pullRequest=1585) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-service?pullRequest=1585) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-service?pullRequest=1585) it.</sub>

2023-05-02 15:12 UTC, Tschakki approved these changes

2023-05-05 07:17 UTC, nagdahimanshu approved these changes

2023-05-05 08:23 UTC, sameersubudhi requested changes
The examples on the page seem outdated and need to be updated.
1. `Prepare the transaction object` section doesn't make sense here. It has to be done outside of the Lisk Service.
2. `Prepare the transaction object > via CLI`: Example is outdated
3. `Prepare the transaction object > via API Client`: Example is outdated
4. `Sending the transaction > via HTTP API`: `http://localhost:9901/api/v2/transactions` must be `http://localhost:9901/api/v3/transactions`
5. `Sending the transaction > via WebSocket API`: `rpc-v2` must be replaced with `rpc-v3`
6. Additionally, it'd probably be nicer to have `Via` replaced with `via`?

2023-05-05 09:42 UTC, chris529 commented
@sameersubudhi Many thanks. As discussed, the relevant outdated points will be addressed in the new issue #1776
https://github.com/LiskHQ/lisk-docs/issues/1776

2023-05-05 09:42 UTC, sameersubudhi approved these changes

2023-05-12 11:42 UTC, merged