Unable to start connector service against betanet
LiskHQ/lisk-service pull request #1590
Opened 2023-04-21 17:37 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1589 

### How was it solved?
- [ ] Fix issue with connector

### How was it tested?
Local against betanet

2023-04-22 00:02 UTC, sameersubudhi requested changes

2023-04-22 00:02 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/genesisBlock.js
> +	if (totalUsers !== 0) {
Lets discuss the details offline.

2023-04-24 16:52 UTC, priojeetpriyom commented on services/blockchain-connector/shared/sdk/blocksUtils.js
> +			throw err;
Applied.

2023-04-25 21:01 UTC, sameersubudhi approved these changes

2023-04-25 21:12 UTC, sameersubudhi approved these changes

2023-04-26 08:37 UTC, priojeetpriyom approved these changes

2023-04-26 08:39 UTC, sameersubudhi approved these changes

2023-04-26 08:39 UTC, merged