Blockchain application off-chain meta endpoint does not adhere to the limits
LiskHQ/lisk-service pull request #1627
Opened 2023-05-04 15:34 UTC by vardan10

### What was the problem?
This PR resolves #1609 

### How was it solved?

- [x] Sliced array to adhere to limit passed
- [x] Fixed integration test cases

### How was it tested?

- [x] Integration tests
- [x] APIs

2023-05-04 20:02 UTC, sameersubudhi requested changes
Please consider the following.

2023-05-04 20:02 UTC, sameersubudhi commented on services/blockchain-app-registry/shared/metadata.js
>  	}
I'd prefer to not modify the params.
```suggestion
	if (params.isDefault !== true && blockchainAppsMetadata.data.length < params.limit) {
		let offset = { params };

		// If params.isDefault is not passed in the request then adjust the offset
		if (!('isDefault' in params)) {
			const totalDefaultApps = await applicationMetadataTable.count(
				{ ...params, limit, isDefault: true },
			);

			offset = (params.offset - totalDefaultApps) > 0 ? params.offset - totalDefaultApps : 0;
		}

		const nonDefaultApps = await applicationMetadataTable.find(
			{ ...params, offset, limit, isDefault: false },
			['network', 'appDirName', 'isDefault'],
		);

		blockchainAppsMetadata.data.push(...nonDefaultApps);
	}
```

2023-05-05 08:16 UTC, sameersubudhi approved these changes
LGTM 👍

2023-05-05 12:33 UTC, nagdahimanshu approved these changes
LGTM 👍

2023-05-05 12:33 UTC, merged