Fix revertTransaction hook for submitSidechainCrossChainUpdate transaction
LiskHQ/lisk-service pull request #1676
Opened 2023-06-01 09:18 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1625 

### How was it solved?
- [ ] TODO

### How was it tested?
Local

2023-06-01 21:39 UTC, sameersubudhi requested changes
Looks good overall but please consider the following.

2023-06-01 21:39 UTC, sameersubudhi commented on services/blockchain-indexer/shared/database/schema/ccu.js
> +		id: { type: 'string', null: false },
```suggestion
	primaryKey: 'transactionID',
	schema: {
		transactionID: { type: 'string', null: false },
```

2023-06-01 21:39 UTC, sameersubudhi commented on services/blockchain-indexer/jobs/indexer/deleteCCU.js
> + * Copyright © 2022 Lisk Foundation
```suggestion
 * Copyright © 2023 Lisk Foundation
```

2023-06-01 21:39 UTC, sameersubudhi commented on services/blockchain-indexer/jobs/indexer/deleteCCU.js
I'd rename the file to `deleteFinalisedCCUMetadata.js` or something similar. Also, please rename the config, job and methods accordingly. The name `deleteCCU` can be quite confusing/misleading for users.

2023-06-01 21:39 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js
> +);
With the latest mysql updates, we don't need to specify the table name anymore.
```suggestion
const getCCUTable = () => getTableInstance(ccuTableSchema, MYSQL_ENDPOINT);
const getTransactionsTable = () => getTableInstance(transactionsTableSchema, MYSQL_ENDPOINT);
```

2023-06-01 21:39 UTC, sameersubudhi commented on services/blockchain-indexer/shared/jobs/deleteCCU.js
> +);
```suggestion
const getCCUTable = () => getTableInstance(ccuTableSchema, MYSQL_ENDPOINT);
```

2023-06-02 08:15 UTC, nagdahimanshu commented on services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js
> +	const prevTransactionHeight = Math.max(...resultSet.map(trx => trx.height));
Done! Thanks for the suggestion 👍

2023-06-02 09:14 UTC, priojeetpriyom approved these changes

2023-06-02 11:18 UTC, vardan10 approved these changes

2023-06-02 11:18 UTC, vardan10 commented on services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js
> +	await ccuTable.upsert({ ...tx, ...tx.params, transactionID: tx.id }, dbTrx);
Should we specify the params for better readability? 
```suggestion
	await ccuTable.upsert({ height: tx.height, sendingChainID: tx.params.sendingChainID, transactionID: tx.id }, dbTrx);
```

2023-06-05 08:12 UTC, sameersubudhi requested changes

2023-06-05 08:12 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/interoperability/submitSidechainCrossChainUpdate.js
> +			limit: 1,
On the mainchain, a single block can contain multiple `.submitSideChainCrossChainUpdate` transactions from various `sendingChainIDs`. Also, we need to ensure that the relevant `prevTx.executionStatus` was success else fetch even older relevant transaction.

Ideally with `if (tx.executionStatus !== TRANSACTION_STATUS.SUCCESS) return;` within the hooks, the above shouldn't be an issue but it's better to cover any possible failure scenarios to make the code robust.

2023-06-05 10:47 UTC, sameersubudhi approved these changes

2023-06-05 10:50 UTC, merged