Update docker setup guide - Closes 1647
LiskHQ/lisk-service pull request #1701
Opened 2023-06-19 15:42 UTC by TalhaMaliktz

### What was the problem?
Closes #1647

2023-06-20 13:21 UTC, Tschakki requested changes

2023-06-20 13:21 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +* Alternatively, you can setup up a node for a sidechain, as described in the xref:{url_build_blockchain}[] section.
Imho link to the developer guides are not fitting here. Probably, a direct link to the app-registry would be cool here, once it is available.

For now, maybe you can just link to the sidechain definition https://lisk.com/documentation/beta/understand-blockchain/interoperability/index.html#mainchain-sidechains

```suggestion
* Alternatively, you can setup up a sidechain node to connect to Lisk Service.
```

2023-06-20 13:21 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +- The *default* API port for *HTTP* & *WebSocket* is: `7887`
I don't think the port changed

2023-06-22 15:38 UTC, Tschakki requested changes

2023-06-22 15:38 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
>  More commands about how to manage Lisk Service are described on the xref:{url_management}[Docker commands] page.
Docker commands hasn't been updated, yet. Please comment out the link to the page.

2023-06-22 15:38 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +The aforementioned example assumes that the blockchain node e.g. Lisk Core node is running on the host machine, and not inside of a Docker container.
```suggestion
The `example.env` assumes that the blockchain node e.g. Lisk Core node is running on the host machine, and not inside of a Docker container.
```

I would also move this statement above the code snippet.

2023-06-23 13:11 UTC, Tschakki approved these changes
LGTM 🎉

2023-06-24 08:54 UTC, sameersubudhi requested changes
Please consider the following.

2023-06-24 08:54 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +* Alternatively, you can setup up a sidechain node to connect to Lisk Service.
Could you also please add a note to emphasize that setting the `system.keepEventsForHeights: -1` in the config is very important when setting up the node?

```suggestion
* To set up a Lisk-Core node, see any of our setup guides, such as xref:{url_core_setup_npm}[].
* Alternatively, you can setup up a sidechain node to connect to Lisk Service.
* Please make sure to set `system.keepEventsForHeights: -1` in the node config before synchronizing the node with the network.
```

2023-06-24 08:54 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Working directory: /lisk-service/
Using root directory maybe a wrong assumption. Maybe use the relative path?
```suggestion
.Working directory: ./lisk-service/
```
or
```suggestion
.Working directory: <download_directory>/lisk-service/
```

2023-06-24 08:54 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +When running a blockchain node inside of a Docker container, the following variable needs to refer to the container:
```suggestion
When running a blockchain node inside of a Docker container, the following variable needs to refer to the container. For this to work, the container running the blockchain node and the Lisk Service Blockchain Connector container must share the same docker network:
```

2023-06-24 08:54 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Working directory: /lisk-service/
Same as above.

2023-06-24 08:54 UTC, sameersubudhi commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Working directory: /lisk-service/
Same as above.

2023-06-26 22:08 UTC, sameersubudhi approved these changes
Thank you for the changes. LGTM 👍

2023-06-26 22:08 UTC, merged