Update microservice documentation
LiskHQ/lisk-service pull request #1702
Opened 2023-06-20 14:33 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1684 

### How was it solved?

- [ ] Update all microservices `readme` to include all configuration parameters

### How was it tested?
Local

2023-06-24 08:12 UTC, sameersubudhi requested changes

2023-06-26 10:28 UTC, chris529 requested changes
Looks good, just some minor points.. 👍

2023-06-26 13:21 UTC, sameersubudhi commented on services/blockchain-indexer/README.md
> +- `JOB_SCHEDULE_DELETE_SERIALIZED_EVENTS`: Job run cron schedule to delete serialized events. By default, it is set to run every 5th minute (`*/5 * * * *`).
@chris529 `5th minute` is correct since the jobs are supposed to run on 5, 10, 15... 55th minutes of any given hour.

2023-06-26 13:22 UTC, sameersubudhi commented on services/blockchain-indexer/README.md
> +- `JOB_INTERVAL_VALIDATE_VALIDATORS_RANK`: Job run interval to validate validators rank. By default, it is set to 0.
`Job run interval to validate the rank for all the validators. By default, it is set to 0.`

2023-06-26 13:22 UTC, sameersubudhi commented on services/blockchain-indexer/README.md
> +- `JOB_SCHEDULE_REFRESH_ACCOUNT_KNOWLEDGE`: Job run cron schedule to refresh account knowledge. By default, it is set to run every 15th minute (`*/15 * * * *`).
Same as above.

2023-06-26 13:24 UTC, sameersubudhi commented on services/transaction-statistics/README.md
> +- `JOB_SCHEDULE_REFRESH_TRANSACTION_STATS`: Job run cron schedule to refresh transaction statistics. By default, it is set to run every 30th minute (`*/30 * * * *`).
Same as above.

2023-06-26 13:25 UTC, sameersubudhi commented on services/transaction-statistics/README.md
> +- `JOB_INTERVAL_VERIFY_TRANSACTION_STATS`: Job run interval to verify if transaction statistics has been build properly. By default, it is set to 0.
`Job run interval to verify if the transaction statistics have been built correctly. By default, it is set to 0.`

2023-06-27 08:55 UTC, sameersubudhi approved these changes
LGTM 👍

2023-06-27 08:59 UTC, chris529 commented on services/blockchain-indexer/README.md
> +- `JOB_SCHEDULE_DELETE_SERIALIZED_EVENTS`: Job run cron schedule to delete serialized events. By default, it is set to run every 5th minute (`*/5 * * * *`).
@sameersubudhi Ah ha..OK, understood. 👍

2023-06-27 09:09 UTC, chris529 approved these changes
LGTM! 👍

2023-06-27 09:09 UTC, merged