Unhandled exception when filename for transaction history download is a directory
LiskHQ/lisk-service pull request #1726
Opened 2023-07-03 13:23 UTC by vardan10

### What was the problem?
This PR resolves #1716 

### How was it solved?
- [x] Handle errors related to file reads within the downloadTransactionHistory method.
- [ ] Add a check to the httpHandler method to ensure that the error corresponds to a valid HTTP status code
- [x] Add necessary pattern checks for query params for the export API

### How was it tested?
- [ ] Local

2023-07-04 14:30 UTC, sameersubudhi commented on services/gateway/apis/http-exports/methods/export.js
> +		filename: { optional: false, type: 'string', pattern: regex.FILEPATH },
```suggestion
		filename: { optional: false, type: 'string', pattern: regex.CSV_EXPORT_FILENAME },
```

2023-07-04 15:31 UTC, sameersubudhi requested changes

2023-07-04 15:31 UTC, sameersubudhi commented on services/export/shared/csvExport.js
>  	const isFileExists = await staticFiles.exists(filename);
Please add a regex test (`CSV_EXPORT_FILENAME.test(filename)`) at the beginning to validate the `filename`.

2023-07-04 15:31 UTC, sameersubudhi commented on services/export/shared/csvExport.js
> +	if (!isFile) throw new ValidationException(`${filename} is not a file.`);
Could we also ensure that we return a `400 BAD REQUEST` response from the controller when we throw the ValidationException?

2023-07-04 16:46 UTC, nagdahimanshu commented on services/export/shared/helpers/file.js
> +const isFile = async (filePath) => fs.lstatSync(filePath).isFile();
Can we update is to use `lstat` instead of `lstatSync`?

2023-07-05 22:04 UTC, sameersubudhi requested changes

2023-07-05 22:04 UTC, sameersubudhi commented on services/export/shared/helpers/s3.js
> +				resolve(0);
Shouldn't the return value be an object? `stat.size` below would throw an error. Alternatively, we can directly resolve the boolean value within the callback if..else ladder.
```suggestion
				resolve({ size: 0 });
```

2023-07-06 10:21 UTC, vardan10 commented on services/export/shared/helpers/file.js
>  const read = (filePath) => new Promise((resolve, reject) => {
Moved this change outside read function.

2023-07-06 19:56 UTC, sameersubudhi approved these changes
LGTM 👍

2023-07-06 19:56 UTC, sameersubudhi commented on services/export/shared/csvExport.js
> +const { CSV_EXPORT_FILENAME } = require('./regex');
```suggestion
const regex = require('./regex');
```

2023-07-06 19:56 UTC, sameersubudhi commented on services/export/shared/csvExport.js
> +	if (!CSV_EXPORT_FILENAME.test(filename)) {
Just so that it is clear and intuitive when reading through the code 🙂 
```suggestion
	if (!regex.CSV_EXPORT_FILENAME.test(filename)) {
```

2023-07-07 08:34 UTC, nagdahimanshu approved these changes
Looks good 👍

2023-07-07 08:34 UTC, merged