Incorrect transaction minFee/size
LiskHQ/lisk-service pull request #1729
Opened 2023-07-07 09:27 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1604 

### How was it solved?

- [ ] Verify the current implementation
- [ ] Add logic to consider additionalFee if applicable for min fee calculation
- [ ] Update `docker/example.env` file
- [ ] Update `ecosystem.config.js` file

### How was it tested?
Local

2023-07-10 10:33 UTC, sameersubudhi requested changes

2023-07-10 10:33 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js
> +			&& event.data.address === tx.params.recipientAddress);
The transaction ID should also be present in the event topics.

2023-07-10 10:33 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js
> +		tx.minFee = formattedTransaction ? formattedTransaction.minFee : tx.minFee;
Same for other places.
```suggestion
		tx.minFee = formattedTransaction.minFee;
```

2023-07-10 10:33 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js
> +	}
Same as above.

2023-07-10 10:33 UTC, sameersubudhi commented on services/blockchain-indexer/shared/indexer/transactionProcessor/pos/registerValidator.js
> +	tx.minFee = formattedTransaction ? formattedTransaction.minFee : tx.minFee;
Same as above.

2023-07-10 12:02 UTC, sameersubudhi approved these changes
LGTM 👍

2023-07-11 09:18 UTC, vardan10 approved these changes

2023-07-11 09:18 UTC, vardan10 commented on ecosystem.config.js
>  				HTTP_RATE_LIMIT_NUM_KNOWN_PROXIES: 0,
```suggestion
                                HTTP_RATE_LIMIT_ENABLE_X_FORWARDED_FOR: 'false',
				HTTP_RATE_LIMIT_NUM_KNOWN_PROXIES: 0,
```

2023-07-11 09:49 UTC, sameersubudhi approved these changes

2023-07-11 09:49 UTC, merged