Fix knex timeout errors
LiskHQ/lisk-service pull request #1733
Opened 2023-07-11 10:43 UTC by priojeetpriyom

### What was the problem?
This PR resolves #1564

### How was it solved?
- [x] Use absolute ip (127.0.0.1) instead of `localhost` in mysql connection string
 
### How was it tested?
- [ ] Local

2023-07-11 13:39 UTC, sameersubudhi requested changes

2023-07-11 13:39 UTC, sameersubudhi commented on services/blockchain-app-registry/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./
This change seems unnecessary.

2023-07-11 13:39 UTC, sameersubudhi commented on services/blockchain-coordinator/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./.npmrc ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on services/blockchain-indexer/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./.npmrc ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on services/export/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on services/fee-estimator/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./.npmrc ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on services/gateway/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on services/template/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json ./
Same as above.

2023-07-11 13:39 UTC, sameersubudhi commented on tests/Dockerfile
> +COPY --chown=lisk:lisk ./package-lock.json ./package.json .babelrc ./
Same as above.

2023-07-13 09:09 UTC, chris529 approved these changes
LGTM! 👍

2023-07-14 08:19 UTC, Nazgolze approved these changes

2023-07-14 10:54 UTC, nagdahimanshu approved these changes

2023-07-14 11:02 UTC, sameersubudhi approved these changes

2023-07-14 11:02 UTC, merged