Align code snippets
LiskHQ/lisk-service pull request #1764
Opened 2023-07-26 14:27 UTC by Tschakki

### What was the problem?
This PR resolves #1724

2023-07-27 12:59 UTC, TalhaMaliktz requested changes
Looking good!

2023-07-27 12:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/source.adoc
Snippets need an update on lines 200, 208, 212, 218, and 222.

2023-07-27 12:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
>  ----
I would format it like this:
```suggestion
. Clone Lisk Service repository.
+
----
git clone https://github.com/LiskHQ/lisk-service.git
----
. Change working directory to the new repository.
+
----
cd lisk-service
----
. Switch to the release branch.
+
----
git checkout v0.7.0
----
```

2023-07-27 12:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/source.adoc
>  git clone https://github.com/LiskHQ/lisk-service.git
The source needs an update. Same suggestion for this as mentioned above for the `setup/docker.adoc`.

2023-07-27 12:59 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/management/docker.adoc
>  ----
```suggestion
.Execute command in running docker container.
----
sudo docker exec -it lisk-service_redis_core_persistent_1 /bin/sh
----

.Truncate redis database.
----
redis-cli flushall
----
```

2023-07-28 10:15 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Working directory: lisk-service/
`./` indicates the current folder, so imho it doesn't fit here in the caption. It assumes the user is one folder up from the `lisk-service` folder, but in fact the user should be inside the `lisk-service` folder, that's why i would remove it

2023-07-28 10:20 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +----
```suggestion

----
git clone https://github.com/LiskHQ/lisk-service.git
----

----
cd lisk-service
----

Switch to the latest release branch.

----
```

2023-07-28 10:26 UTC, Tschakki commented on docs/antora/modules/ROOT/pages/setup/source.adoc
>  . Install v16 of Node.js using NVM.
Good catch, I created a corresponding issue: #1768

2023-07-28 10:32 UTC, TalhaMaliktz commented on docs/antora/modules/ROOT/pages/setup/docker.adoc
> +.Working directory: lisk-service/
I see, In that case, I also would update lines 173, 201, and 209 to align content.

2023-07-28 11:23 UTC, TalhaMaliktz approved these changes
Thank you! Just a minor change! rest LGTM

2023-07-28 11:34 UTC, chris529 approved these changes
LGTM! 👍

2023-08-03 15:23 UTC, merged