Keep list of pending transactions up to date - Closes #140
LiskHQ/lisk-service pull request #178
Opened 2020-11-04 10:54 UTC by nagdahimanshu

### What was the problem?
This PR resolves #140 

### How was it solved?
- [ ] Pending transactions need to be available and the list has to be up-to-date
- [ ] List of transactions has to be refreshed in short intervals (1s)

### How was it tested?
Local

2020-11-06 10:47 UTC, sameersubudhi approved these changes
LGTM 👍

2020-11-10 11:22 UTC, MichalTuleja requested changes

2020-11-10 11:22 UTC, MichalTuleja commented on services/core/methods/controllers/transactions.js
> +		links: result.links,
Links are not needed here.

2020-11-10 11:22 UTC, MichalTuleja commented on services/core/shared/core/transactions.js
> +					tx.confirmations =						latestBlock.confirmations + latestBlock.height - tx.height;
Indentation?

2020-11-10 11:35 UTC, nagdahimanshu commented on services/core/methods/controllers/transactions.js
> +		links: result.links,
Removed!

2020-11-10 11:36 UTC, nagdahimanshu commented on services/core/shared/core/transactions.js
> +					tx.confirmations =						latestBlock.confirmations + latestBlock.height - tx.height;
Fixed indentation.

2020-11-11 16:27 UTC, MichalTuleja requested changes

2020-11-11 16:27 UTC, MichalTuleja commented on services/core/shared/core/transactions.js
> +const formatSortString = (sortString) => {
Please update formatting

2020-11-11 16:27 UTC, MichalTuleja commented on services/core/shared/core/transactions.js
> +const getTransactions = async (params) => {
Please update formatting

2020-11-11 16:27 UTC, MichalTuleja commented on services/core/shared/core/transactions.js
> +				dbResult.map((tx) => {
Please update formatting

2020-11-12 17:04 UTC, MichalTuleja approved these changes

2020-11-12 17:04 UTC, merged