API client not subscribing to events
LiskHQ/lisk-service pull request #1839
Opened 2023-09-07 09:44 UTC by nagdahimanshu

### What was the problem?
This PR resolves #1820 

### How was it solved?

- [ ] Add logic to verify client connection
- [ ] Configure number of blocks to verify client connection

### How was it tested?
Local

2023-09-07 15:12 UTC, priojeetpriyom commented on services/blockchain-connector/shared/sdk/events.js
> +	}, BLOCK_TIME * numOfBlocksVerify);
If we recreate a connection that is not broken, could it create any issue for ongoing node calls? Also, would it be better to reuse [getApiClient](https://github.com/LiskHQ/lisk-service/blob/51b074adc43117d70d514fc622f4ce7b8d09c402/services/blockchain-connector/shared/sdk/client.js#L85) logic, which already checks for broken connection and recreates it? Also, we do not need the `numOfBlocksReset` logic in this case.

```suggestion
	setInterval(getApiClient, BLOCK_TIME * numOfBlocksVerify);
```

2023-09-07 15:12 UTC, priojeetpriyom commented on services/blockchain-connector/shared/sdk/client.js
> +const instantiateClient = async (isForceUpdate = false) => {
We may not need this incase we go with the other suggestion

```suggestion
const instantiateClient = async () => {
```

2023-09-07 15:12 UTC, priojeetpriyom commented on services/blockchain-connector/config.js
> +	numOfBlocksVerify: process.env.NUM_BLOCKS_VERIFY || 15,
Just a preferential suggestion, would something like `connectionVerifyBlockInterval` be more suitable naming?

2023-09-08 14:22 UTC, sameersubudhi requested changes

2023-09-08 14:22 UTC, sameersubudhi commented on services/blockchain-connector/config.js
> +	numOfBlocksReset: process.env.NUM_BLOCKS_RESET || 10,
Why do we need two of them? Only one should be enough 🤔 
We must reset the connection only when we do not receive events for specified number of blocks (i.e. for configured numBlocks * blockTime).

2023-09-08 14:22 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/events.js
> +const verifyClientConnection = async () => {
I'd move all this logic to `client.js` and use Signals to communicate the receipt of events over the API client.

2023-09-08 14:22 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/index.js
> +	await verifyClientConnection();
This may not be necessary. The verification logic can be an IIFE within `client.js`.

2023-09-14 15:02 UTC, sameersubudhi approved these changes

2023-09-15 12:48 UTC, vardan10 approved these changes

2023-09-15 12:52 UTC, merged