Make integration tests schema based - Closes #150
LiskHQ/lisk-service pull request #192
Opened 2020-11-13 13:51 UTC by sameersubudhi

### What was the problem?
This PR resolves #150 

### How was it solved?
- [ ] Make all the integration tests schema based, agnostic of the environment
- [ ] Refactor all the tests to reuse a single set of the schema for various environments

### How was it tested?
Local + Jenkins

2020-11-30 09:38 UTC, nagdahimanshu commented on tests/helpers/socketIoRpcRequest.js
> +		resolve(answer);
```suggestion
		if (answer.error) reject(answer);
		resolve(answer);
```

2020-11-30 09:46 UTC, nagdahimanshu commented on tests/integration/api/http/networkSearch.test.js
> +		expect(response).toMap(notFoundSchema);
```suggestion
		expect(response).toMap(badRequestSchema);
```

2020-11-30 09:47 UTC, nagdahimanshu commented on tests/integration/api/http/networkSearch.test.js
> +		expect(response).toMap(notFoundSchema);
```suggestion
		expect(response).toMap(badRequestSchema);
```

2020-11-30 09:47 UTC, nagdahimanshu commented on tests/integration/api/http/networkSearch.test.js
> +	notFoundSchema,
```suggestion
	badRequestSchema,
```

2020-11-30 10:10 UTC, nagdahimanshu requested changes
looks good apart from small suggestions

2020-12-01 09:28 UTC, nagdahimanshu approved these changes

2020-12-01 14:51 UTC, MichalTuleja approved these changes

2020-12-01 14:51 UTC, merged