Add receivingChainID request param support to transactions endpoint
LiskHQ/lisk-service pull request #1934
Opened 2023-11-22 07:46 UTC by vardan10

### What was the problem?
This PR resolves https://github.com/LiskHQ/lisk-service/issues/1931

### How was it solved?
- [x] Added support for receivingChainID to be currentChainID in transactions API
- [ ] Fix TODOs

### How was it tested?
Local

2023-11-22 17:06 UTC, sameersubudhi requested changes

2023-11-22 17:06 UTC, sameersubudhi commented on services/blockchain-connector/shared/sdk/schema.js
>  const getDataSchemaByEventName = eventName => {
Please update the method as discussed offline to cache the events by module and eventName instead.

2023-11-22 17:06 UTC, sameersubudhi commented on services/blockchain-indexer/shared/dataService/business/pendingTransactions.js
> +	// If recieving chainID is current chain ID then return all transactions with receivingChainID = null
```suggestion
	// If receivingChainID is currentChainID then return all the transactions where receivingChainID = null
```

2023-11-23 14:08 UTC, sameersubudhi approved these changes
The fixes seem to work as expected, except for the issue reported in https://github.com/LiskHQ/lisk-service/issues/1937.

2023-11-23 14:22 UTC, priojeetpriyom approved these changes

2023-11-23 14:46 UTC, merged