Switch event implementation to signals - Closes #186
LiskHQ/lisk-service pull request #197
Opened 2020-11-17 17:41 UTC by MichalTuleja

### What was the problem?
This PR resolves #186

### How was it solved?

- [ ] Signal library is applied
- [ ] Events are propagated in the SDKv2
- [ ] Events are propagated in the SDKv3
- [ ] Events are propagated in the SDKv4

### How was it tested?

Manually

2020-11-23 09:09 UTC, sameersubudhi commented on services/core/shared/core/delegateUtils.js
> +	if (dbResult.length === 1) return dbResult[0].username;
`getAddressByUsername` must return the delegate address.

```suggestion
	if (dbResult.length === 1) return dbResult[0].address;
```

2020-11-23 09:18 UTC, sameersubudhi requested changes
Apart from the suggested logical fix, the remaining code changes look good.

2020-11-23 09:29 UTC, nagdahimanshu reviewed
Given branch is behind the development, pull the change before merge (Y).

2020-11-23 09:37 UTC, nagdahimanshu approved these changes
Looks good!

2020-11-24 08:24 UTC, nagdahimanshu approved these changes
Looks good!

2020-11-24 09:09 UTC, sameersubudhi approved these changes

2020-11-24 11:11 UTC, merged