Retrieve current forgers - Closes #240
LiskHQ/lisk-service pull request #302
Opened 2021-01-13 09:03 UTC by nagdahimanshu

### What was the problem?
This PR resolves #240 

### How was it solved?
- [ ] HTTP /api/v2/forgers works
- [ ]  RPC get.forgers works
- [ ] Retrieval of next forgers is possible
- [ ] Gateway is updated with the API version 2
- [ ] response map properly

### How was it tested?
Local

2021-01-21 10:08 UTC, sameersubudhi requested changes
The implementation looks good. However, please consider my remarks below. They are all good to have.

2021-01-21 10:08 UTC, sameersubudhi commented on services/core/shared/core/delegates.js
> +	}
Please test if this works.

```suggestion
	nextForgers = await BluebirdPromise.map(
		rawNextForgers,
		async forger => sdkVersion <= 4
			? delegateList.find(o => o.address === forger.address)
			: forger,
	);
```

2021-01-21 10:08 UTC, sameersubudhi commented on services/core/shared/core/compat/sdk_v5/forgers.js
> +		forger.totalVotesReceived = Number(filterAcc[0].dpos.delegate.totalVotesReceived);
```suggestion
		const filteredAcc = forgerAccounts.data
			.filter(account => account.address.toString('hex') === forger.address);
		forger.username = filteredAcc[0].dpos.delegate.username;
		forger.totalVotesReceived = Number(filteredAcc[0].dpos.delegate.totalVotesReceived);
```

2021-01-21 10:49 UTC, nagdahimanshu commented on services/core/events/blockchain.js
> +				}
Done, thanks!

2021-01-21 10:49 UTC, nagdahimanshu commented on services/gateway/app.js
> +		})),
Done!

2021-01-21 10:49 UTC, nagdahimanshu commented on services/core/shared/core/delegates.js
> +	}
Done!

2021-01-22 08:57 UTC, MichalTuleja commented on services/gateway/app.js
> +		})),
Actually, all of them should be doing that, this is why we've got a separate config files.

2021-01-22 09:22 UTC, MichalTuleja approved these changes

2021-01-22 09:30 UTC, merged