Export transaction schemas - Closes #389
LiskHQ/lisk-service pull request #409
Opened 2021-03-18 16:27 UTC by sameersubudhi

### What was the problem?
This PR resolves #389

### How was it solved?
- [x] Add the following endpoints in `gateway` to fetch the schemas
  - [x] HTTP: `/api/v2/transactions/schemas`
  - [x] RPC: `get.transactions.schemas`
- [ ] Support filtering based on the following request params:
  - [ ] `moduleAssetId`
  - [ ] `moduleAssetName`
- [ ] Add integration tests
  - [ ] HTTP
  - [ ] RPC

### How was it tested?
Local + Jenkins

2021-03-22 12:39 UTC, nagdahimanshu approved these changes
Looks good apart from one suggestion!

2021-03-22 12:39 UTC, nagdahimanshu commented on services/gateway/sources/version2/transactionsSchemas.js
> + * Copyright © 2020 Lisk Foundation
```suggestion
 * Copyright © 2021 Lisk Foundation
```

2021-03-24 13:31 UTC, MichalTuleja requested changes

2021-03-24 13:31 UTC, MichalTuleja commented on services/core/shared/core/compat/sdk_v5/transactionsSchemas.js
> +	}
Cache is not needed here.

2021-03-24 13:34 UTC, sameersubudhi commented on services/core/shared/core/compat/sdk_v5/transactionsSchemas.js
> +	}
Removed the caching behaviour.

2021-03-24 13:45 UTC, MichalTuleja approved these changes

2021-03-24 13:45 UTC, merged