Account endpoint is missing public key param - Closes #406
LiskHQ/lisk-service pull request #411
Opened 2021-03-21 22:13 UTC by sameersubudhi

### What was the problem?
This PR resolves #406 

### How was it solved?
- [x] Update 'publickey' request param to 'publicKey'
- [x] Update all tests cases to reflect the change
- [x] Update `dpos.unlocking` mapping schema at gateway

### How was it tested?
Local + Jenkins

2021-03-22 12:43 UTC, nagdahimanshu requested changes

2021-03-22 12:43 UTC, nagdahimanshu commented on tests/schemas/api_v2/account.schema.js
> + * Copyright © 2020 Lisk Foundation
```suggestion
 * Copyright © 2021 Lisk Foundation
```

2021-03-22 12:43 UTC, nagdahimanshu commented on tests/schemas/api_v2/delegate.schema.js
> + * Copyright © 2020 Lisk Foundation
```suggestion
 * Copyright © 2021 Lisk Foundation
```

2021-03-22 13:11 UTC, nagdahimanshu approved these changes

2021-03-24 13:09 UTC, MichalTuleja approved these changes

2021-03-24 14:21 UTC, merged