Transaction/block filter support for half bounded ranges - Closes #435
LiskHQ/lisk-service pull request #446
Opened 2021-04-07 14:50 UTC by nagdahimanshu

### What was the problem?
This PR resolves #435 

### How was it solved?
- [x] Support half bounded ranges for transactions
  - [x] Support for `amount`
  - [x] Support for `timestamp`
- [x] Support half bounded ranges for blocks
  - [x] Support for `height`
  - [ ] Support for `timestamp`

### How was it tested?
- [ ] Local
- [ ] Jenkins

2021-04-08 20:18 UTC, sameersubudhi requested changes

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			const { result } = response;
```suggestion
			const { result } = response;
			expect(result.data).toBeInstanceOf(Array);
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			});
```suggestion
			expect(result.data[0]).toMap(blockSchemaVersion5);
			result.data.forEach((blockItem) => {
				expect(blockItem).toMap(blockSchemaVersion5);
				expect(blockItem.timestamp).toBeGreaterThanOrEqual(from);
			});
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			});
```suggestion
			const { result } = response;
			expect(result.data).toBeInstanceOf(Array);
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
			result.data.forEach((blockItem) => {
				expect(blockItem).toMap(blockSchemaVersion5);
				expect(blockItem.timestamp).toBeLessThanOrEqual(to);
			});
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			});
```suggestion
			const { result } = response;
			expect(result.data).toBeInstanceOf(Array);
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
			result.data.forEach((blockItem) => {
				expect(blockItem).toMap(blockSchemaVersion5);
				expect(blockItem.height).toBeGreaterThanOrEqual(minHeight);
				expect(blockItem.height).toBeLessThanOrEqual(maxHeight);
			});
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			});
```suggestion
			const { result } = response;
			expect(result.data).toBeInstanceOf(Array);
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
			result.data.forEach((blockItem) => {
				expect(blockItem).toMap(blockSchemaVersion5);
				expect(blockItem.height).toBeGreaterThanOrEqual(minHeight);
			});
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			});
```suggestion
			const { result } = response;
			expect(result.data).toBeInstanceOf(Array);
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
			result.data.forEach((blockItem) => {
				expect(blockItem).toMap(blockSchemaVersion5);
				expect(blockItem.height).toBeLessThanOrEqual(maxHeight);
			});
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/transactions.test.js
> +			expect(result.data.length).toBeGreaterThanOrEqual(1);
```suggestion
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/transactions.test.js
> +			expect(result.data.length).toBeGreaterThanOrEqual(1);
```suggestion
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/transactions.test.js
> +			expect(result.data.length).toBeGreaterThanOrEqual(1);
```suggestion
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/transactions.test.js
> +			expect(result.data.length).toBeGreaterThanOrEqual(1);
```suggestion
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-08 20:18 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/transactions.test.js
> +			expect(result.data.length).toBeGreaterThanOrEqual(1);
```suggestion
			expect(result.data.length).toBeGreaterThanOrEqual(1);
			expect(result.data.length).toBeLessThanOrEqual(10);
```

2021-04-09 08:06 UTC, sameersubudhi requested changes

2021-04-09 08:06 UTC, sameersubudhi commented on tests/integration/api_v2/http/transactions.test.js
> +			const from = moment(refTransaction.block.timestamp).subtract(1, 'day').unix() * (10 ** 3);
```suggestion
			const from = moment(refTransaction.block.timestamp * 10 ** 3).subtract(1, 'day').unix();
```

2021-04-09 08:06 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			const from = 0;
Please consider using the `refBlock.timestamp` instead.
```suggestion
			const from = refBlock.timestamp - 100;
```

2021-04-09 08:06 UTC, sameersubudhi commented on tests/integration/api_v2/rpc/blocks.test.js
> +			const minHeight = 0;
Please consider using the `refBlock.height`.
```suggestion
			const minHeight = refBlock.height - 10;
```

2021-04-09 08:11 UTC, nagdahimanshu commented on tests/schemas/transaction.schema.js
> +	signatures: Joi.array().items(Joi.string().allow('').optional()).required(),
I think in case of `SDKv5`, empty string are allowed for array of signatures. There are some transactions with signatures as empty string

2021-04-09 09:00 UTC, sameersubudhi approved these changes
LGTM! 👍

2021-04-12 13:07 UTC, MichalTuleja approved these changes

2021-04-12 15:44 UTC, merged