424 api updates
LiskHQ/lisk-service pull request #482
Opened 2021-04-26 14:34 UTC by MichalTuleja

### What was the problem?
This PR resolves #424

### How was it solved?

- [x] Updated block parameter
- [ ] Update response schema
- [ ] Update tests
- [ ] Update documentation
- [ ] Minor refactor 

### How was it tested?

Jenkins

2021-04-27 17:30 UTC, nagdahimanshu approved these changes
LGTM!

2021-04-27 17:35 UTC, sameersubudhi requested changes

2021-04-27 17:35 UTC, sameersubudhi commented on docs/api/version2.md
> +search ie. "gene*" -> "genesis"                       |
Seems inconsistent.

2021-04-28 12:35 UTC, chris529 reviewed
Hi Michal, Looks very good, just a couple of very small points. 👍

2021-04-28 12:35 UTC, chris529 commented on docs/config_options.md
> +Note that most of them are set properly in the Docker environment.
```suggestion
Note that most of them are set correctly in the Docker environment.
```

2021-04-28 12:35 UTC, chris529 commented on docs/config_options.md
> +If the Docker environment is being used, the only required variable `LISK_CORE_WS` is needed.
```suggestion
If the Docker environment is being used, only the required variable `LISK_CORE_WS` is needed.
```

2021-04-28 13:53 UTC, sameersubudhi approved these changes

2021-04-28 14:03 UTC, merged