Sorting by amount returns null values - Closes #499
LiskHQ/lisk-service pull request #500
Opened 2021-05-04 10:36 UTC by sameersubudhi

### What was the problem?
This PR resolves #499 

### How was it solved?
- [x] Perform sorting only on non-null values
- [x] Merge sorting based test cases from PR https://github.com/LiskHQ/lisk-service/pull/497
- [x] Enable disabled transactions test cases 

### How was it tested?
Local + Jenkins

2021-05-04 12:43 UTC, nagdahimanshu requested changes
Please consider one suggestion!

2021-05-04 12:43 UTC, nagdahimanshu commented on services/core/shared/indexdb/mysql.js
> +			query.whereNotNull(sortProp);
It works well but returns incorrect count. Now, we need to add given logic to our count function as well to get exact count: 
```
if (params.sort) {
  const [sortProp, sortOrder] = params.sort.split(':');
  query.orderBy(sortProp, sortOrder);
  query.whereNotNull(sortProp);
}
```

2021-05-04 13:30 UTC, nagdahimanshu approved these changes
LGTM!

2021-05-05 09:36 UTC, MichalTuleja approved these changes
LGTM 👍

2021-05-05 09:36 UTC, merged