Retrieve market prices core - Closes #464
LiskHQ/lisk-service pull request #518
Opened 2021-05-12 08:25 UTC by nagdahimanshu

### What was the problem?
This PR resolves #464 

### How was it solved?
- [ ] Added methods/controllers in `services/market`
- [ ] Added placeholder for implementation and return mock data
- [ ] Update `gateway` to use method name as per specs document
- [ ] Added functional tests

### How was it tested?
- [ ] Local
- [ ] Jenkins

2021-05-18 08:59 UTC, sameersubudhi requested changes
Please find a couple of minor observations.

2021-05-18 09:05 UTC, nagdahimanshu commented on Jenkinsfile
> +		stage('Run microservices') {
The reason to perform unit tests after all services started is to run the functional tests for market service which requires  services `services/market/tests/functional/market.prices.test.js` else test will always fail with error `market service not found`

``` const result = await broker.call('market.prices', {});```

2021-05-18 10:33 UTC, nagdahimanshu commented on Jenkinsfile
> +		stage('Run microservices') {
As we discussed, I added separate stage for functional tests in `Jenkins`.

2021-05-18 10:50 UTC, nagdahimanshu commented on services/market/tests/functional/market.prices.test.js
> +                }));
Done!

2021-05-18 12:03 UTC, sameersubudhi approved these changes
LGTM overall 👍  
However, please consider the following nomenclature recommendation.

2021-05-18 12:03 UTC, sameersubudhi commented on services/market/tests/functional/market.prices.test.js
> +const marketPriceSchema = Joi.object({
```suggestion
const marketPriceItemSchema = Joi.object({
```

2021-05-18 12:03 UTC, sameersubudhi commented on services/market/tests/functional/market.prices.test.js
> +            result.data.forEach(price => marketPriceSchema.validate(price));
```suggestion
            result.data.forEach(price => marketPriceItemSchema.validate(price));
```

2021-05-19 14:12 UTC, MichalTuleja approved these changes

2021-05-19 14:12 UTC, merged