Add exchangeratesapi.io data source - Closes #468
LiskHQ/lisk-service pull request #533
Opened 2021-05-19 13:31 UTC by nagdahimanshu

### What was the problem?
This PR resolves #468 

### How was it solved?
- [x] Add job `prices.retrieve.exchangeratesapi` to retrieve data from `exchangeratesapi.io` api
- [x] Transform data according to the requirement
- [x] Store transformed data from `exchangeratesapi.io` into `redis` cache
- [x] Add function `getExchangeratesapiPricesFromDB` to retrieve latest prices from `exchangeratesapi.io` cache
- [x] Added `ttl` of 24 hours and make request only when data is expired

### How was it tested?
- [x] Local
- [x] Jenkins

2021-05-20 08:59 UTC, sameersubudhi requested changes
Please find a few observations/recommendations below.

2021-05-20 08:59 UTC, sameersubudhi commented on services/market/config.js
> +config.access_key.exchangeratesapi = 'e27c981843d2d08916cf4e3864f5a92b';
Please consider passing on sensitive information such as `access keys` via environment variables.

2021-05-20 08:59 UTC, sameersubudhi commented on services/market/shared/market/sources/exchangeratesapi.js
> +        return allMarketTickers;
As a good to have, please consider removing the `baseCurrency` from the `symbols` list as the relationship would always be a constant equal to `1`.

Also, please consider renaming the methods/variables to be more appropriate and reflective of their purpose.

```suggestion
const fetchAllCurrencyConversionRates = async () => {
    try {
        const allMarketConversionRates = {};
        await BluebirdPromise.all(
            currencies.map(async (baseCurrency) => {
                const remainingCurrencies = currencies.filter(c => c !== baseCurrency);
                const response = await requestLib(`${apiEndpoint}/latest?access_key=${accessKey}&base=${baseCurrency}&symbols=${remainingCurrencies.join(',')}`);
                if (response) allMarketConversionRates[baseCurrency] = response.data.rates;
            }),
        );
        return allMarketConversionRates;
```

2021-05-20 08:59 UTC, sameersubudhi commented on services/market/shared/market/sources/exchangeratesapi.js
> +};
Same as above. Please consider renaming `prices` to `conversionRates` instead!?

2021-05-20 08:59 UTC, sameersubudhi commented on services/market/shared/market/sources/exchangeratesapi.js
> +};
Same as above.
Also, please consider adding `ttl` value as a top-level file constant or an entry in the config file.

```suggestion
const reloadPricesFromExchangerateapi = async () => {
    const conversionRatesFromCache = await getExchangeratesapiPricesFromDB();

    // Check if prices exists in cache
    if (!conversionRatesFromCache) {
        const currencyConversionRates = await fetchAllCurrencyConversionRates();
        const transformedRates = standardizeCurrencyConversionRates(currencyConversionRates);

        // Serialize individual price item and write to the cache
        await BluebirdPromise.all(transformedRates
            .map(item => exchangeratesapiCache.set(`exchangeratesapi_${item.code}`, JSON.stringify(item), 24 * 60 * 60 * 1000)));
    }
};
```

2021-05-20 13:11 UTC, sameersubudhi approved these changes
Looks good. Thank you 👍

2021-05-25 16:44 UTC, MichalTuleja approved these changes

2021-05-25 16:44 UTC, merged