Fix delegate rank calculation - Closes #638
LiskHQ/lisk-service pull request #639
Opened 2021-07-16 17:19 UTC by nagdahimanshu

### What was the problem?
This PR resolves #638 

### How was it solved?
- [ ] Implemented logic to update only specific delegates which get updated on every block (instead of updating the whole list)
- [ ] Update cron job to schedule `reloadDelegatesCache` in every 5 minutes
 
### How was it tested?
Local + Jenkins

2021-07-16 18:45 UTC, sameersubudhi requested changes
Please find my review.

2021-07-16 18:45 UTC, sameersubudhi commented on services/core/shared/core/delegates.js
> +});
Delegate `rank` would vary only when the `voteWeight` changes and the `status` gets updated at the beginning of a new round. 

```suggestion
// Keep the delegate cache up-to-date
Signals.get('newBlock').add(async data => {
	const dposModuleId = 5;
	const voteDelegateAssetId = 1;

	const updatedDelegateAddresses = [];

	const [block] = data.data;
	if (block && block.payload) {
		block.payload.forEach(tx => {
			if (tx.moduleID === dposModuleId && tx.assetID === voteDelegateAssetId) {
				tx.asset.votes.forEach(vote => updatedDelegateAddresses
					.push(coreApi.getBase32AddressFromHex(vote.delegateAddress)));
			}
		});

		const { data: updatedDelegateAccounts } = await coreApi
			.getAccounts({ addresses: updatedDelegateAddresses });

		updatedDelegateAccounts.forEach(delegate => {
			const delegateIndex = delegateList.findIndex(acc => acc.address === delegate.address);
			if (delegateIndex === -1) delegateList.push(delegate);
			else delegateList[delegateIndex] = delegate;
		});

		// Rank is impacted only when a delegate gets (un-)voted
		if (updatedDelegateAddresses.length) await computeDelegateRank();
	}
});
```

2021-07-19 16:10 UTC, MichalTuleja approved these changes

2021-07-19 19:54 UTC, sameersubudhi approved these changes
LGTM 👍

2021-07-19 19:54 UTC, merged