:recycle: Update domain lisk.io to lisk.com
LiskHQ/lisk-service pull request #664
Opened 2021-08-02 07:27 UTC by ManuGowda

### What was the problem?

- The lisk domain was changed from lisk.io to lisk.com, which was not reflected in codebase

### How was it solved?

- Updated all the domain references

### How was it tested?

- Click on new domain links and check if they navigate to correct page

2021-08-02 16:34 UTC, MichalTuleja reviewed
There's still quite a few spots with `.io` suffix. I need to confirm with DevOps which are already updated before updating them and merging.

2021-08-02 20:16 UTC, ManuGowda commented
> There's still quite a few spots with `.io` suffix. I need to confirm with DevOps which are already updated before updating them and merging.

Let me know the missing places, I will update them 👍🏼

2021-08-03 12:46 UTC, MichalTuleja commented
@ManuGowda I've updated the docs & configs, can you please have a final look?

2021-08-03 14:15 UTC, sameersubudhi requested changes
Kindly consider the following remarks.

2021-08-03 14:15 UTC, sameersubudhi commented on README.md
> +Lisk Service consists of several separate modules, that can be run independently from the others. The Gateway is required to expose the APIs provided by the specific services.
```suggestion
Lisk Service consists of several separate modules, that can be run independently from the others. The Gateway is required to expose the APIs provided by the specific services via HTTP and WS protocols.
```

2021-08-03 14:15 UTC, sameersubudhi commented on README.md
> +When running a local instance of Lisk Core and Lisk Service that is run by Docker, then the following variable needs to be set: `LISK_CORE_WS="ws://host.docker.internal:8080"`.
```suggestion
When running a local instance of Lisk Core and Lisk Service that is run by Docker, the following variable needs to be set: `LISK_CORE_WS="ws://host.docker.internal:8080"`.
```

2021-08-03 14:15 UTC, sameersubudhi commented on docs/build_from_source.md
> +In order to run them successfully, it is necessary to have the template component running alongside.
```suggestion
In order to run them all successfully, it is necessary to have the template component running alongside.
```

2021-08-03 14:15 UTC, sameersubudhi commented on README.md
> +- Lisk Service is configured to connect a local node on port 4000 by default.
```suggestion
- Lisk Service is configured to connect a local node via WS on port 8080 by default.
```

2021-08-03 14:44 UTC, nagdahimanshu approved these changes
LGTM 👍

2021-08-03 14:47 UTC, sameersubudhi approved these changes
LGTM 👍

2021-08-03 15:34 UTC, merged