Add job to verify transaction statistics - Closes #660
LiskHQ/lisk-service pull request #665
Opened 2021-08-03 15:07 UTC by nagdahimanshu

### What was the problem?
This PR resolves #660 

### How was it solved?
- [ ] Schedule new job `verify.transaction.statistics` (ebery 3 hours)
- [ ] Implement new method `updateTransactionStatistics` that verify stats based on tx type

### How was it tested?
Local + Jenkins

2021-08-04 13:45 UTC, sameersubudhi requested changes
Kindly consider the following:

2021-08-04 13:45 UTC, sameersubudhi commented on services/core/jobs/verifyTransactionStatistics.js
> +
Please consider moving the job to `services/core/jobs/transactionStatistics.js`.

2021-08-04 13:45 UTC, sameersubudhi commented on services/core/jobs/transactionStatistics.js
> +			}
Please consider wrapping all the jobs within `try...catch` and output a warning log upon error.

2021-08-04 13:45 UTC, sameersubudhi commented on services/core/shared/core/transactionStatistics.js
> +const updateTransactionStatistics = async historyLengthDays => {
Please consider updating the method name to reflect its exact utility.

```suggestion
const verifyTransactionStatistics = async historyLengthDays => {
```
or
```suggestion
const verifyAndUpdateTransactionStatistics = async historyLengthDays => {
```
or
```suggestion
const validateTransactionStatistics = async historyLengthDays => {
```

2021-08-04 14:21 UTC, sameersubudhi commented on services/core/shared/core/transactionStatistics.js
> +	if (!isStatisticsBuilt) await fetchTransactionsForPastNDays(historyLengthDays, true);
Kindly consider simplifying the code to something similar to:

```suggestion
	const isStatsProperlyBuilt = verifyStatistics.every(isVerified => isVerified);
	if (!isStatsProperlyBuilt) await fetchTransactionsForPastNDays(historyLengthDays, true);
```

2021-08-05 10:59 UTC, sameersubudhi approved these changes
Thank you for the changes. Works very well 👍

2021-08-10 13:40 UTC, MichalTuleja approved these changes

2021-08-10 13:40 UTC, merged