Fix produced blocks and rewards calculation - Closes #676
LiskHQ/lisk-service pull request #679
Opened 2021-08-06 14:40 UTC by nagdahimanshu

### What was the problem?
This PR resolves #676 

### How was it solved?
- [ ] Fix `indexAccountsbyPublicKey` method

### How was it tested?
- [ ] Locally against `testnet`

2021-08-09 16:26 UTC, sameersubudhi commented
Kindly consider the following changes:
1. Checking for missing blocks within the `else` section of `checkIndexReadiness` in `services/core/shared/core/compat/sdk_v5/blocks.js`.
```
			} else {
				logger.debug('Blocks index is not yet ready');
				await indexMissingBlocks(getIndexStartHeight(), currentChainHeight);
			}
```
2. Update the delegate cache with the `producedBlocks` and `rewards`information on the `newBlock` and `deleteBlock` events.

2021-08-09 16:27 UTC, sameersubudhi requested changes
Please check the above recommendations.

2021-08-11 09:30 UTC, sameersubudhi requested changes
We still have an unhandled scenario described below:

An account isn't a delegate anymore when the block containing their delegate registration transaction gets rolled back (`deleteBlock` event). This change should be reflected within our delegate cache as well.

In case of any doubts, we can clarify it offline.

2021-08-12 15:55 UTC, sameersubudhi approved these changes

2021-08-12 15:56 UTC, MichalTuleja approved these changes

2021-08-12 15:56 UTC, merged