Retry failed Lisk Core request - Closes #680
LiskHQ/lisk-service pull request #689
Opened 2021-08-11 14:55 UTC by sameersubudhi

### What was the problem?
This PR resolves #680 

### How was it solved?
- [x] Add retry support to coreApi
- [ ] Retry querying `getLastBlock` on exception
- [ ] Ensure indexing of the last block on exception
- [ ] Ensure to broadcast the last block even on exception

### How was it tested?
Local

2021-08-13 08:33 UTC, MichalTuleja requested changes

2021-08-13 08:33 UTC, MichalTuleja commented on services/core/shared/core/compat/sdk_v5/accounts.js
> +		? await coreApi.requestWithRetries(coreApi.getAccountsByAddresses, params.addresses)
Can you please add 
```
const requestApi = coreApi.requestWithRetries;
```
at the beginning of those files?

I would advise to use some shorter name btw, such as `requestWithRetries -> requestRetry`

2021-08-13 08:33 UTC, MichalTuleja commented on services/core/jobs/missingBlocks.js
> +		schedule: '15 * * * *', // Every hour at the 15th minute
```suggestion
		schedule: '*/15 * * * *', // 15-minute interval
```

2021-08-13 09:43 UTC, nagdahimanshu approved these changes
Looks good and works as expected 👍

2021-08-13 13:56 UTC, MichalTuleja requested changes

2021-08-13 13:56 UTC, MichalTuleja commented on services/core/jobs/missingBlocks.js
> +		schedule: '*/15 * * * *', // 15-minute interval
```suggestion
		schedule: '45 * * * *', // 1 hour interval
```

2021-08-16 13:40 UTC, MichalTuleja approved these changes
LGTM 👍

2021-08-16 13:41 UTC, merged