Cache accounts - Closes #688
LiskHQ/lisk-service pull request #690
Opened 2021-08-11 18:49 UTC by sameersubudhi

### What was the problem?
This PR resolves #688 

### How was it solved?
- [x] Use Redis configuration to keep the most often used accounts (LRU-policy)
- [x] Account retrieval from Lisk Core always updates the Redis LRU cache
- [x] Created a different function to retrieve cached account data
- [x] Always fetch account from the cache, if unavailable fetch from Core

### How was it tested?
Local

2021-08-13 08:57 UTC, nagdahimanshu approved these changes
LGTM 👍

2021-08-13 10:06 UTC, MichalTuleja requested changes

2021-08-13 10:06 UTC, MichalTuleja commented on services/core/shared/core/compat/sdk_v5/accounts.js
> +	CacheLRU,
This LRU-cache implementation doesn't use Redis. Please make it Redis-based.

2021-08-13 13:59 UTC, MichalTuleja requested changes

2021-08-13 13:59 UTC, MichalTuleja commented on services/core/shared/core/compat/sdk_v5/accounts.js
> +const accountsCache = CacheRedis('accounts', config.endpoints.redis);
```suggestion
const accountsCache = CacheRedis('accounts', config.endpoints.volatileRedis);
```

2021-08-17 13:50 UTC, MichalTuleja approved these changes
The implementation looks good. Let's perform final tests on continuous delivery.

2021-08-17 13:50 UTC, merged