Documentation update - Closes #699
LiskHQ/lisk-service pull request #701
Opened 2021-08-18 09:19 UTC by MichalTuleja

### What was the problem?
This PR resolves #699

### How was it solved?
- [ ] Updated Readme
- [ ] Updated configuration

### How was it tested?
n/a

2021-08-18 10:38 UTC, sameersubudhi requested changes
Please find a couple of suggestions.

2021-08-18 10:38 UTC, sameersubudhi commented on README.md
> +It is strongly recommended to sync Lisk Core with the network **before** starting Lisk Service.
```suggestion
It is strongly recommended to synchronize your Lisk Core node with the network **before** starting the Lisk Service.
```

2021-08-18 10:38 UTC, sameersubudhi commented on docs/config_options.md
> +# This should be a different instance on production
```suggestion
# This should be a separate instance in the production
```

2021-08-19 07:46 UTC, chris529 approved these changes
Looks good 👍

2021-08-19 08:35 UTC, sameersubudhi approved these changes
LGTM 👍

2021-08-19 09:52 UTC, merged