Create microservice for multisignature pool - Closes #159
LiskHQ/lisk-service pull request #707
Opened 2021-08-20 09:29 UTC by nagdahimanshu

### What was the problem?
This PR resolves #159 

### How was it solved?
- [ ] New microservice (`transaction`) is ready: starts and registers in the gateway properly
- [ ] New microservice is mentioned in the readme file
- [ ] Update readme for newsfeed service

### How was it tested?
Local + Jenkins

2021-08-20 14:50 UTC, sameersubudhi requested changes
Please consider the following:

2021-08-20 14:50 UTC, sameersubudhi commented on services/transaction/config.js
> +config.brokerTimeout = Number(process.env.SERVICE_BROKER_TIMEOUT) || 5; // in seconds
Please update the config to keep consistency across all the microservices. Please make sure to update the template as well.
```suggestion
config.brokerTimeout = Number(process.env.SERVICE_BROKER_TIMEOUT) || 10; // in seconds
```

2021-08-20 14:50 UTC, sameersubudhi commented on README.md
> +| [Newsfeed](services/newsfeed) | The news feed service is a one-purpose microservice that polls the content sharing platforms and shares collected data with UI clients such as Lisk Desktop |
```suggestion
| [Newsfeed](services/newsfeed) | The Newsfeed service is a single-purpose microservice that polls the content sharing platforms and shares collected data with UI clients such as Lisk Desktop |
```

2021-08-20 14:50 UTC, sameersubudhi commented on README.md
> +| [Transaction](services/transaction) | The Transaction service is a proxy between all participants before the multisignature transaction is ready to broadcast |
```suggestion
| [Transaction](services/transaction) | The Transaction service is a proxy between all participants before a multisignature transaction is ready to be broadcast to the blockchain |
```

2021-08-20 14:50 UTC, sameersubudhi commented on services/newsfeed/README.md
> +The news feed service is a one-purpose microservice that polls the content sharing platforms and shares collected data with UI clients such as Lisk Desktop
```suggestion
The Newsfeed service is a single-purpose microservice that polls the content sharing platforms and shares collected data with UI clients such as Lisk Desktop
```

2021-08-20 14:50 UTC, sameersubudhi commented on services/transaction/README.md
> +The Transaction service is a proxy between all participants before the multisignature transaction is ready to broadcast
```suggestion
The Transaction service is a proxy between all participants before a multisignature transaction is ready to be broadcast to the blockchain
```

2021-08-20 17:08 UTC, sameersubudhi approved these changes
LGTM 👍

2021-08-31 13:44 UTC, MichalTuleja approved these changes
LGTM!

2021-08-31 13:44 UTC, merged