Improve websocket rate limits - Closes #722
LiskHQ/lisk-service pull request #739
Opened 2021-08-31 17:51 UTC by nagdahimanshu

### What was the problem?
This PR resolves #722 

### How was it solved?
- [ ] TODO

### How was it tested?
Local + Jenkins

2021-09-02 09:08 UTC, sameersubudhi requested changes

2021-09-02 09:08 UTC, sameersubudhi commented on ecosystem.jenkins.config.js
> +				ENABLE_WS_RATELIMIT: false,
Please add the following environment variables as well and please update as a comment if `WS_RATELIMIT_DURATION` is in seconds or millisecs. The same config needs to be updated for `gateway` microservice in `ecosystem.core3.config.js` file as well.
```suggestion
				ENABLE_WS_RATELIMIT: false,
				WS_RATELIMIT_POINTS: 5,
				WS_RATELIMIT_DURATION: 1, // in seconds
```

2021-09-02 09:08 UTC, sameersubudhi commented on services/gateway/config.js
> +	enableRateLimit: Boolean(String(process.env.ENABLE_WS_RATELIMIT).toLowerCase() !== 'false'),
Let us disable `enableRateLimit` until and unless `ENABLE_WS_RATELIMIT` is explicitly set to `true`.

```suggestion
	enableRateLimit: Boolean(String(process.env.ENABLE_WS_RATELIMIT).toLowerCase() === 'true'),
```

2021-09-02 09:13 UTC, sameersubudhi commented
@nagdahimanshu Please make sure to update the respective docker environment files as well.

2021-09-02 11:07 UTC, sameersubudhi approved these changes
👍

2021-09-03 08:41 UTC, MichalTuleja requested changes
@nagdahimanshu Can you please also mention those settings in the documentation?

2021-09-03 11:37 UTC, MichalTuleja approved these changes

2021-09-03 11:37 UTC, merged