Create Jenkinsfile for weekly mainnet tests - Closes #845
LiskHQ/lisk-service pull request #860
Opened 2021-11-10 15:51 UTC by nagdahimanshu

### What was the problem?
This PR resolves #845

### How was it solved?

- [ ] Create Jenkinsfile that runs Lisk Service against Mainnet and triggers full indexing.
- [ ] Create Jenkinsfile that runs regression tests on the full blockchain index.
- [ ] Create Jenkinsfile that runs performance tests on the full blockchain index.

### How was it tested?
Jenkins

2021-11-19 10:49 UTC, MichalTuleja requested changes
Few things need to be clarified. Are the tests already run on Jenkins?

2021-11-19 10:49 UTC, MichalTuleja commented on Jenkinsfile.deployment.mainnet
> +						sh 'make up-custom-core3-cd'
I think this script is already removed. `make up` with right params should do the job.

2021-11-19 10:49 UTC, MichalTuleja commented on Jenkinsfile.performance.mainnet
> +		cron('0 0 * * 0')
Assuming the deployment is performed at 12:00pm, the test can be delayed one hour or so. To make sure the process works stable and there are no pending background tasks.

2021-11-19 10:49 UTC, MichalTuleja commented on Jenkinsfile.regression.mainnet
> +		cron('0 0 * * 0')
Same as above.

2021-12-31 10:02 UTC, ManuGowda approved these changes

2021-12-31 10:02 UTC, merged