Mitigate MySQL layer deadlock issue - Closes #820
LiskHQ/lisk-service pull request #960
Opened 2022-02-03 13:55 UTC by sameersubudhi

### What was the problem?
This PR resolves #820 

### How was it solved?
- [x] Deadlocks are expected, so added user-friendly error logging when DB deadlocks are encountered
```
2022-02-03T14:55:46.873 WARN [queue] indexAccountsQueue Job failed,Deadlock encountered when indexing block at height 17651205. Will retry later.
2022-02-03T14:55:46.873 WARN [queue] indexAccountsQueue Job failed,Error: Deadlock encountered when indexing block at height 17651205. Will retry later.
    at Queue.indexBlocks ([/Users/sameer/Documents/Lisk/github/lisk-service/services/core/shared/core/compat/sdk_v5/blockchainIndex.js:245:10]())
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal[/process/task_queues.js:97:5]())
```
- [x] Fix `getTransactions` invocation in `validateTransactionStatistics`

### How was it tested?
Local

2022-02-04 17:27 UTC, MichalTuleja requested changes
Looks better now. Is there any way to remove the stack trace from the second message?

```
core_1              | 2022-02-04T17:23:57.065 WARN [queue] indexAccountsQueue Job failed,Deadlock encountered while indexing block at height 17683105. Will retry later.
core_1              | 2022-02-04T17:23:57.065 WARN [queue] indexAccountsQueue Job failed,Error: Deadlock encountered while indexing block at height 17683105. Will retry later.
core_1              |     at Queue.indexBlocks (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/blockchainIndex.js:245:10)
core_1              |     at runMicrotasks (<anonymous>)
core_1              |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

2022-02-04 17:30 UTC, nagdahimanshu commented
> Looks better now. Is there any way to remove the stack trace from the second message?
> 
> ```
> core_1              | 2022-02-04T17:23:57.065 WARN [queue] indexAccountsQueue Job failed,Deadlock encountered while indexing block at height 17683105. Will retry later.
> core_1              | 2022-02-04T17:23:57.065 WARN [queue] indexAccountsQueue Job failed,Error: Deadlock encountered while indexing block at height 17683105. Will retry later.
> core_1              |     at Queue.indexBlocks (/home/lisk/lisk-service/core/shared/core/compat/sdk_v5/blockchainIndex.js:245:10)
> core_1              |     at runMicrotasks (<anonymous>)
> core_1              |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```

@MichalTuleja I think this can be only ignored if we update our queue implementation
```
		queue.on('failed', (job, err) => {
			if (err .message.includes('Deadlock encountered')) {
				logger.warn(`${jobName} Job failed`, err.message);
				return;
			}
			logger.warn(`${jobName} Job failed`, err.message);
			logger.warn(`${jobName} Job failed`, err.stack);
		});

2022-02-04 17:54 UTC, sameersubudhi commented
> Looks better now. Is there any way to remove the stack trace from the second message?

@MichalTuleja No, not unless we customise the queue implementation to ignore logging in this particular case. We can consider enhancing the queue implementation to support whitelisting known errors mentioned within a config file, in a separate issue. Something for the future.

2022-02-11 17:31 UTC, MichalTuleja approved these changes

2022-02-11 17:31 UTC, merged